In [16]:
class Demo:
    def __init__(self,name):
        self.name=name
        print("constrctor called ",self.name)
    def __del__(self):
        print("destroctor called ",self.name)


obj=Demo("virat")
del obj


    

constrctor called  virat
destroctor called  virat


In [21]:
class Parent:
    def greet(self):
        print("greeting from parent")

class Child(Parent):
    def greet(self):
        print("gretting from child")


p1=Parent()
c1=Child()

p1.greet()
c1.greet()
    

greeting from parent
gretting from child


In [31]:
class Marks:
    def __init__(self,marks):
        self.marks=marks
    def __add__(self,other):
        return self.marks +other.marks

    def __str__(self):
        return f"marks={self.marks}"

m1=Marks(30)
m2=Marks(40)

print(m1+m2)


        

70


In [6]:
class Emp:
    Company_name="TCS"
    Company_emp_count=0

    def __init__(self,name):
        self.name=name
        Emp.Company_emp_count+=1

    @classmethod

    def show_emp_count(cls):
        print("total employee",cls.Company_emp_count)
    @staticmethod
    def show_company_info():
        print("company name",Emp.Company_name)

emp1=Emp("nilesh")
emp2=Emp("abhi")

Emp.show_emp_count()
Emp.show_company_info()
         

total employee 2
company name TCS


In [7]:
import numpy as np

arr1 = np.array([10,20,30,40,50])
arr2 = np.array([[1,2,3],
[4,5,6],
[7,8,9]])

print("1D Array:",arr1)
print("2D Array:\n",arr2)

print("First element:",arr1[0])
print("Element at row2 column3:",arr2[1,2])

print("Slice:",arr1[1:4])

result = arr1 + 10
print("Broadcasting result:",result)

1D Array: [10 20 30 40 50]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First element: 10
Element at row2 column3: 6
Slice: [20 30 40]
Broadcasting result: [20 30 40 50 60]


In [8]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)

print("Mean:",np.mean(a))

c = np.arange(12)
matrix = c.reshape(3,4)

print("Matrix:\n",matrix)
print("Transpose:\n",matrix.T)

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]
Mean: 2.5
Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [9]:
import pandas as pd

data=[10,20,30,40,50]
series=pd.Series(data)

print(series)

student={
"Name":["Rahul","Sneha","Amit","Priya"],
"Age":[20,21,19,22],
"Marks":[85,90,75,88]
}

df=pd.DataFrame(student)

print(df)

print(df["Name"])

print(df[df["Marks"]>80])

0    10
1    20
2    30
3    40
4    50
dtype: int64
    Name  Age  Marks
0  Rahul   20     85
1  Sneha   21     90
2   Amit   19     75
3  Priya   22     88
0    Rahul
1    Sneha
2     Amit
3    Priya
Name: Name, dtype: object
    Name  Age  Marks
0  Rahul   20     85
1  Sneha   21     90
3  Priya   22     88


In [11]:
import pandas as pd
import numpy as np

data={
"Name":["Rahul","Sneha","Amit","Priya","Karan"],
"Age":[20,np.nan,19,22,21],
"Marks":[85,90,np.nan,88,76]
}

df=pd.DataFrame(data)

print(df)

df["Age"].fillna(df["Age"].mean(),inplace=True)
df["Marks"].fillna(df["Marks"].mean(),inplace=True)

print(df)

sorted_df=df.sort_values(by="Marks",ascending=False)

print(sorted_df)

df["Rank"]=df["Marks"].rank(ascending=False)
print(df)

print(df.describe())

    Name   Age  Marks
0  Rahul  20.0   85.0
1  Sneha   NaN   90.0
2   Amit  19.0    NaN
3  Priya  22.0   88.0
4  Karan  21.0   76.0


<ipython-input-11-0490af908c84>:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)
<ipython-input-11-0490af908c84>:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try usi

    Name   Age  Marks
0  Rahul  20.0  85.00
1  Sneha  20.5  90.00
2   Amit  19.0  84.75
3  Priya  22.0  88.00
4  Karan  21.0  76.00
    Name   Age  Marks
1  Sneha  20.5  90.00
3  Priya  22.0  88.00
0  Rahul  20.0  85.00
2   Amit  19.0  84.75
4  Karan  21.0  76.00
    Name   Age  Marks  Rank
0  Rahul  20.0  85.00   3.0
1  Sneha  20.5  90.00   1.0
2   Amit  19.0  84.75   4.0
3  Priya  22.0  88.00   2.0
4  Karan  21.0  76.00   5.0
             Age      Marks      Rank
count   5.000000   5.000000  5.000000
mean   20.500000  84.750000  3.000000
std     1.118034   5.356071  1.581139
min    19.000000  76.000000  1.000000
25%    20.000000  84.750000  2.000000
50%    20.500000  85.000000  3.000000
75%    21.000000  88.000000  4.000000
max    22.000000  90.000000  5.000000


In [21]:
# Writing into file
file = open("sample.txt", "w")
file.write("Welcome to Python File Handling.\n")
file.write("Second Line.\n")
file.write("Third Line.\n")
file.close()

# Using read()
file = open("sample.txt", "r")
print("Using read():")
print(file.read())
file.close()

# Using readline()
file = open("sample.txt", "r")
print("Using readline():")
print(file.readline())
print(file.readline())
file.close()

# Using readlines()
file = open("sample.txt", "r")
print("Using readlines():")
print(file.readlines())
file.close()

Using read():
Welcome to Python File Handling.
Second Line.
Third Line.

Using readline():
Welcome to Python File Handling.

Second Line.

Using readlines():
['Welcome to Python File Handling.\n', 'Second Line.\n', 'Third Line.\n']


In [22]:
file = open("write_demo.txt", "w")
file.write("Python Programming\n")
file.write("File Handling Example\n")
file.close()

file = open("write_demo.txt", "a")
data = ["Line 3\n", "Line 4\n", "Line 5\n"]
file.writelines(data)
file.close()

file = open("write_demo.txt", "r")
print(file.read())
file.close()

Python Programming
File Handling Example
Line 3
Line 4
Line 5



In [24]:
file = open("pointer_demo.txt", "w+")
file.write("Python File Pointer Example")

file.seek(0)
print("Initial Position:", file.tell())

data = file.read(6)
print("Read Data:", data)

print("Position after reading:", file.tell())

file.seek(7)

print("Pointer moved to:", file.tell())

print("Remaining Data:", file.read())

file.close()

# Key Concepts
# seek(n) → move pointer to position n
# tell() → get current position
# read(n) → read n characters

Initial Position: 0
Read Data: Python
Position after reading: 6
Pointer moved to: 7
Remaining Data: File Pointer Example
